name: Project CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Project initialized
        run: echo "Repository initialized successfully"