"""Persistence and setup inference ports owned by the CI context."""

from __future__ import annotations

from typing import Protocol

from app.modules.competitive_intelligence.models import (
    CreateWatchlist, ProductProfileVersion, Revision, UpdateWatchlist, Watchlist,
)
from app.modules.runs.models import RunDocument


class IntelligenceRepository(Protocol):
    async def create(self, request: CreateWatchlist, owner_id: str) -> Watchlist: ...
    async def get(self, watchlist_id: str, owner_id: str) -> Watchlist: ...
    async def list(self, owner_id: str, limit: int, offset: int) -> list[Watchlist]: ...
    async def update(self, watchlist_id: str, owner_id: str, request: UpdateWatchlist) -> Watchlist: ...
    async def revisions(self, watchlist_id: str, owner_id: str) -> list[Revision]: ...
    async def approve(self, watchlist_id: str, revision_id: str, owner_id: str, version_id: str) -> Revision: ...
    async def archive(self, watchlist_id: str, owner_id: str) -> None: ...
    async def admit_run(self, document: RunDocument, watchlist_id: str, revision_id: str) -> RunDocument: ...
    async def runs(self, watchlist_id: str, owner_id: str, limit: int, offset: int) -> list[RunDocument]: ...
    async def workflow_id(self, version_id: str, owner_id: str) -> str: ...
    async def count(self, owner_id: str, watchlist_id: str | None = None) -> int: ...
    async def profiles(self, watchlist_id: str, product_id: str, owner_id: str) -> list[ProductProfileVersion]: ...


class SetupPlanner(Protocol):
    async def propose(self, messages: list[dict[str, str]]) -> CreateWatchlist: ...
