"""Persistence and setup inference ports owned by the CI context."""

from __future__ import annotations

from typing import Protocol

from app.modules.competitive_intelligence.models import (
    CreateWatchlist, ProductProfileVersion, Revision, UpdateWatchlist, Watchlist,
)
from app.modules.competitive_intelligence.snapshot_contracts import (
    ChangeCandidate, FetchOutcome, RunSourceComparison, SourceSnapshot,
)
from app.modules.competitive_intelligence.brief_contracts import IntelligenceBrief
from app.modules.competitive_intelligence.investigation_contracts import InvestigationRound
from app.modules.runs.models import RunDocument


class IntelligenceRepository(Protocol):
    async def create(self, request: CreateWatchlist, owner_id: str) -> Watchlist: ...
    async def get(self, watchlist_id: str, owner_id: str) -> Watchlist: ...
    async def list(self, owner_id: str, limit: int, offset: int) -> list[Watchlist]: ...
    async def update(self, watchlist_id: str, owner_id: str, request: UpdateWatchlist) -> Watchlist: ...
    async def revisions(self, watchlist_id: str, owner_id: str) -> list[Revision]: ...
    async def approve(self, watchlist_id: str, revision_id: str, owner_id: str, version_id: str) -> Revision: ...
    async def archive(self, watchlist_id: str, owner_id: str) -> None: ...
    async def admit_run(self, document: RunDocument, watchlist_id: str, revision_id: str) -> RunDocument: ...
    async def runs(self, watchlist_id: str, owner_id: str, limit: int, offset: int) -> list[RunDocument]: ...
    async def workflow_id(self, version_id: str, owner_id: str) -> str: ...
    async def count(self, owner_id: str, watchlist_id: str | None = None) -> int: ...
    async def profiles(self, watchlist_id: str, product_id: str, owner_id: str) -> list[ProductProfileVersion]: ...

    async def pin_baselines(self, watchlist_id: str, owner_id: str) -> dict[str, str | None]: ...


class SnapshotBlobStore(Protocol):
    def put(self, owner_id: str, run_id: str, snapshot_id: str, name: str, text: str) -> str: ...
    def read_span(self, storage_uri: str, start: int, limit: int) -> str: ...
    def read_full(self, storage_uri: str) -> str: ...


class SnapshotRepository(Protocol):
    async def record_outcome(self, outcome: FetchOutcome, owner_id: str) -> FetchOutcome: ...
    async def capture_snapshot(self, outcome: FetchOutcome, snapshot: SourceSnapshot, captured_text: str,
                               normalized_text: str) -> SourceSnapshot: ...
    async def get_snapshot(self, snapshot_id: str, owner_id: str) -> SourceSnapshot: ...
    async def snapshot_text(self, snapshot_id: str, owner_id: str) -> tuple[str, str]: ...
    async def read_snapshot_span(self, snapshot_id: str, owner_id: str, representation: str, start: int,
                                 limit: int) -> str: ...
    async def latest_baseline(self, source_id: str, owner_id: str) -> SourceSnapshot | None: ...
    async def record_comparison(self, comparison: RunSourceComparison, owner_id: str,
                                candidates: list[ChangeCandidate]) -> RunSourceComparison: ...
    async def promote_baseline(self, snapshot: SourceSnapshot, run_id: str,
                               expected_snapshot_id: str | None) -> str: ...
    async def get_change(self, change_id: str, owner_id: str) -> ChangeCandidate: ...
    async def list_comparisons(self, run_id: str, owner_id: str) -> list[RunSourceComparison]: ...
    async def list_candidates(self, run_id: str, owner_id: str,
                              source_id: str | None = None) -> list[ChangeCandidate]: ...
    async def list_snapshots(self, source_id: str, owner_id: str, limit: int) -> list[SourceSnapshot]: ...
    async def list_changes_for_watchlist(self, watchlist_id: str, owner_id: str, limit: int,
                                         offset: int) -> list[ChangeCandidate]: ...
    async def count_changes_for_watchlist(self, watchlist_id: str, owner_id: str) -> int: ...


class InvestigationRepository(Protocol):
    async def save_round(self, round: InvestigationRound, owner_id: str) -> InvestigationRound: ...
    async def get_round(self, round_id: str, owner_id: str) -> InvestigationRound: ...
    async def list_rounds(self, run_id: str, owner_id: str) -> list[InvestigationRound]: ...
    async def set_round_status(self, round_id: str, owner_id: str, status: str, decided_by: str,
                               rejection_reasons: list[str] | None = None) -> InvestigationRound: ...


class BriefRepository(Protocol):
    async def save_brief(self, brief: IntelligenceBrief, owner_id: str) -> IntelligenceBrief: ...
    async def get_brief(self, brief_id: str, owner_id: str) -> IntelligenceBrief: ...
    async def list_briefs(self, watchlist_id: str, owner_id: str, limit: int,
                          offset: int) -> list[IntelligenceBrief]: ...
    async def count_briefs(self, watchlist_id: str, owner_id: str) -> int: ...


class SetupPlanner(Protocol):
    async def propose(self, messages: list[dict[str, str]]) -> CreateWatchlist: ...
