import os
from datetime import datetime
from typing import List, Dict, Optional
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from app.execution.tools.base import ToolRegistry

# Path to sandboxed workspace data directory
WORKSPACE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "workspace_data"))


class SectionItem(BaseModel):
    header: str = Field(description="Section heading/title.")
    content: str = Field(description="Section markdown text content.")


class MarkdownReportInput(BaseModel):
    title: str = Field(description="Title of the Markdown report.")
    summary: Optional[str] = Field(default=None, description="Executive summary or key highlights of the report.")
    sections: List[SectionItem] = Field(description="List of sections containing header and content.")
    filename: str = Field(default="summary_report.md", description="Output Markdown filename (e.g. 'news_summary.md').")


@ToolRegistry.register_tool(name="markdown_report_generator")
@tool("markdown_report_generator", args_schema=MarkdownReportInput)
def markdown_report_generator(
    title: str,
    sections: List[SectionItem],
    summary: Optional[str] = None,
    filename: str = "summary_report.md"
) -> str:
    """
    Generates a structured Markdown report file from collected insights and saves it in the workspace_data/reports directory.
    Use this to publish research reports, summaries, or compiled task artifacts.
    """
    try:
        reports_dir = os.path.join(WORKSPACE_DIR, "reports")
        os.makedirs(reports_dir, exist_ok=True)

        if not filename.endswith(".md"):
            filename += ".md"

        file_path = os.path.join(reports_dir, filename)

        now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

        md_content = [
            f"# {title}\n",
            f"> **Generated by AgentFlow Platform** | *{now_str}*\n",
            "---\n"
        ]

        if summary:
            md_content.append(f"## Executive Summary\n\n{summary}\n\n---\n")

        md_content.append("## Table of Contents\n")
        for idx, sec in enumerate(sections, 1):
            anchor = sec.header.lower().replace(" ", "-")
            md_content.append(f"{idx}. [{sec.header}](#{anchor})")
        md_content.append("\n---\n")

        for sec in sections:
            md_content.append(f"## {sec.header}\n\n{sec.content}\n\n")

        full_text = "\n".join(md_content)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(full_text)

        rel_path = os.path.relpath(file_path, WORKSPACE_DIR)

        return (
            f"Successfully generated Markdown report!\n"
            f"File Path: {file_path}\n"
            f"Relative Sandbox Path: workspace_data/{rel_path}\n"
            f"Report Size: {len(full_text)} characters, {len(sections)} sections."
        )
    except Exception as e:
        return f"Error generating Markdown report: {str(e)}"
